version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "443:443"  # Expose port 443 for HTTPS
    networks:
      - app-network
    volumes:
      - ./backend/server.key:/etc/ssl/private/server.key  # Map server.key for SSL
      - ./backend/server.crt:/etc/ssl/certs/server.crt  # Map server.crt for SSL

networks:
  app-network:
    driver: bridge
